------------------------
------ [ Services ] ------
local HttpService = game:GetService("HttpService")
local RunService = game:GetService("RunService")
local messagingservice = game:GetService("MessagingService")
local DatastoreService = game:GetService("DataStoreService")
local Players = game:GetService("Players")

-------------------------
------ [ Modules ] ------

------------------------
------ [ Varibles ] ------

------------------------
------ [ Tables ] ------
local NotificationService = {}

---------------------------
------ [ Functions ] ------

return NotificationService
